DROP TABLE IF EXISTS Disease;
CREATE TABLE Disease(
   diseaseID   INTEGER  NOT NULL PRIMARY KEY 
  ,diseaseName VARCHAR(100) NOT NULL
  ,description VARCHAR(1000) NOT NULL
);
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (1,'Alzheimer''s disease','Alzheimer''s disease is associated with the bacteria Chlamydia pneumoniae and Helicobacter pylori, and with the protozoan parasite Toxoplasma gondii. Herpes simplex virus 1 is associated with Alzheimer''s disease in individuals who possess the APOE-4 form of the APOE gene (APOE-4 enables the herpes virus to enter the brain).');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (2,'Amyotrophic lateral sclerosis','Amyotrophic lateral sclerosis, the most common of five forms of motor neuron disease, is associated with echovirus (an enterovirus) infection of the central nervous system, and with retrovirus activity (it is not known whether this retrovirus activity arises from a human endogenous retrovirus, or from an exogenous retrovirus).');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (3,'Anorexia nervosa','Infection with Borrelia species bacteria is associated with anorexia nervosa. In rare cases, anorexia nervosa may arise after infection with Streptococcus species bacteria. Anorexia (which is distinct from anorexia nervosa) is associated with the protozoan parasite Dientamoeba fragilis.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (4,'Anxiety disorder','Anxiety is associated with cytomegalovirus, and the bacterium Helicobacter pylori.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (5,'Asthma','Asthma is associated with rhinovirus, human respiratory syncytial virus, and the bacterium Chlamydia pneumoniae. Chlamydia pneumoniae is particularly associated with adult-onset asthma.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (6,'Atherosclerosis','Atherosclerosis is associated with the bacterium Chlamydia pneumoniae.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (7,'Attention deficit hyperactivity disorder','Attention deficit hyperactivity disorder (ADHD) and learning disorders are associated with the bacteria Borrelia burgdorferi and Streptococcus, and with HIV and enterovirus 71. Febrile seizures due to human herpesvirus 6 or influenza A are a risk factor for ADHD. Viral infections during pregnancy, at birth, and in early childhood are risk factors for ADHD.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (8,'Autism','Autism is associated with prenatal maternal infection with rubella virus or cytomegalovirus. Clostridia bacteria species are associated with autism (these bacteria are present in greater numbers in the guts of autistic children).');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (9,'Autoimmune diseases','Autoimmune diseases are strongly associated with enteroviruses such as Coxsackie B virus. Autoimmune diseases are also associated with Epstein-Barr virus, cytomegalovirus, parvovirus B19, and HIV, and the bacterium Mycobacterium tuberculosis. Autoimmune thyroid disease is associated with Epstein-Barr virus and Helicobacter pylori.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (10,'Bipolar disorder','Bipolar disorder is associated with bornavirus, and with Borrelia species bacteria.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (11,'Cancer','Some estimates currently attribute 15% to 20% of all cancers to infectious pathogen causes. In future, this percentage may be revised upwards if the pathogens currently associated with cancers (such as those listed below) are proven to actually cause those cancers. (Note: for the sake of completeness, some infectious pathogens known to cause cancers are included in the list, in addition to the infectious pathogens associated with cancers.)');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (12,'Chronic fatigue syndrome','Chronic fatigue syndrome (also known as myalgic encephalomyelitis) is associated with enteroviruses (such as Coxsackie B virus), human herpesvirus 6 variant A, human herpesvirus 7, and parvovirus B19. The bacteria Coxiella burnetii and Chlamydia pneumoniae are known causes of chronic fatigue syndrome (antibiotics can cure these bacterial forms of chronic fatigue syndrome).');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (13,'Chronic obstructive pulmonary disease','Chronic obstructive pulmonary disease (which includes both chronic bronchitis and emphysema) is associated with Chlamydia pneumoniae and Epstein-Barr virus.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (14,'Crohn''s disease','One study found ileocecal Crohn''s disease is associated with viral species from the enterovirus genus (but note that all the study cohort with ileocecal Crohn''s disease had disease-associated mutations in either their NOD2 or ATG16L1 genes). Crohn''s disease is associated with Mycobacterium avium subspecies paratuberculosis. In a murine model, Crohn''s disease is precipitated by the norovirus CR6 strain, but only in combination with a variant of the Crohn’s susceptibility gene ATG16L1, and chemical toxic damage to the gut. In other words, in this mouse model, Crohn’s is precipitated only when these three causal factors (virus, gene, and toxin) act in combination.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (15,'Coronary heart disease','Coronary heart disease is associated with herpes simplex virus 1 and the bacterium Chlamydia pneumoniae.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (16,'Dementia','Dementia is associated with herpes simplex virus type 1, herpes simplex virus type 2, cytomegalovirus, West Nile virus, bornavirus, and HIV. Dementia is also associated with the helminth Taenia solium (pork tapeworm), and with Borrelia species bacteria.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (17,'Depression','Depression is associated with cytomegalovirus and West Nile virus, and the protozoan parasite Toxoplasma gondii. It is thought that depression may be precipitated by the effect of immune signals (such as pro-inflammatory cytokines) reaching the brain from infections located in the peripheries of the body.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (18,'Diabetes mellitus type 1','Diabetes mellitus type 1 is associated with viral species from the enterovirus genus, specifically echovirus 4 and Coxsackie B virus (the latter it is thought may infect and destroy the insulin producing beta-cells in the pancreas and also damage these cells via indirect autoimmune mechanisms).');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (19,'Diabetes mellitus type 2','Diabetes mellitus type 2 is associated with cytomegalovirus, hepatitis C virus, enteroviruses, and Ljungan virus.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (20,'Dilated cardiomyopathy','Dilated cardiomyopathy is associated with enteroviruses such as Coxsackie B virus.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (21,'Epilepsy','Epilepsy is associated with human herpesvirus 6.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (22,'Guillain–Barré syndrome','Guillain–Barré syndrome is associated with the bacterium Campylobacter jejuni, and with the viruses cytomegalovirus and enterovirus.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (23,'Irritable bowel syndrome','Irritable bowel syndrome (IBS) is associated with the protozoan parasite Giardia lamblia, and pathogenic strains of the protozoan parasite Blastocystis hominis. Irritable bowel syndrome in those with HIV is associated with the protozoan Dientamoeba fragilis. IBS is also associated with the bacterium Mycobacterium avium subspecies paratuberculosis.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (24,'Low back pain','Lower back pain is associated with a spinal disc infection with anaerobic bacteria, especially the bacterium Propionibacterium acnes.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (25,'Lupus','Lupus is associated with the viruses parvovirus B19, Epstein-Barr virus, and cytomegalovirus.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (26,'Metabolic syndrome','Metabolic syndrome is associated with the bacteria Chlamydia pneumoniae and Helicobacter pylori, as well as the viruses cytomegalovirus and herpes simplex virus 1.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (27,'Multiple sclerosis','Multiple sclerosis, a demyelinating disease, is associated with Epstein-Barr virus, human herpesvirus 6, varicella zoster virus, and the bacterium Chlamydia pneumoniae.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (28,'Myocardial infarction','Myocardial infarction (heart attack) is associated with Chlamydia pneumoniae, cytomegalovirus and Coxsackie B virus (an enterovirus). (Coxsackie B virus is also associated with sudden unexpected death due to myocarditis).');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (29,'Obesity','Obesity is associated with adenovirus 36, which is found in 30% of obese people, but only in 11% of non-obese people. It has further been demonstrated that animals experimentally infected with adenovirus 36 (or adenovirus 5, or adenovirus 37) will develop increased obesity. Adenovirus 36 induces obesity by infecting fat cells (adipocytes), wherein the expression of the adenovirus E4orf1 gene turns on both the cell''s fat producing enzymes and also instigates the generation of new fat cells. Evidence suggests that obesity can be a viral disease, and that the worldwide obesity epidemic that began in the 1980s may be in part due to viral infection.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (30,'Obsessive–compulsive disorder','Obsessive–compulsive disorder is associated with Streptococcus and Borrelia species bacteria.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (31,'Panic disorder','Panic disorder is associated with Borrelia and Bartonella species bacteria.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (32,'Parkinson''s disease','Parkinson''s disease is associated with influenza A virus, as well as the protozoan parasite Toxoplasma gondii.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (33,'Psoriasis','Psoriasis is associated with a Helicobacter pylori trigger.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (34,'Rheumatoid arthritis','Rheumatoid arthritis is associated with parvovirus B19. Antibodies to Borrelia outer surface protein A are associated with rheumatoid arthritis.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (35,'Sarcoidosis','Sarcoidosis is associated with Mycobacteria species, and the bacteria Helicobacter pylori and Borrelia burgdorferi.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (36,'Schizophrenia','Schizophrenia is associated with bornavirus, the bacterium Chlamydia trachomatis, as well as Borrelia species bacteria. Schizophrenia is also linked to neonatal infection with Coxsackie B virus (an enterovirus), which one study found carries an increased risk of adult onset schizophrenia. Prenatal exposure to influenza virus in the first trimester of pregnancy increases the risk of schizophrenia by 7-fold.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (37,'Stroke','Stroke is associated with the bacteria Chlamydia pneumoniae, Helicobacter pylori, Mycobacterium tuberculosis, and Mycoplasma pneumoniae, as well as the virus varicella zoster virus and the fungus Histoplasma.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (38,'Thromboangiitis obliterans','Thromboangiitis obliterans is associated with Rickettsia species bacteria.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (39,'Tourette syndrome','Tourette syndrome is associated with the bacterium Streptococcus. Aggravating or contributory microbes in Tourette''s may include the bacteria Mycoplasma pneumoniae, Chlamydia pneumoniae, Chlamydia trachomatis, and the protozoan parasite Toxoplasma gondii.');
INSERT INTO Disease(diseaseID,diseaseName,description) VALUES (40,'Vasculitis','Vasculitis is associated with HIV, parvovirus B19, and hepatitis B virus. The hepatitis C virus is an established cause of vasculitis.');
