ALTER TABLE Patient
MODIFY P_Name VARCHAR(35) NOT NULL;
ALTER TABLE Patient_Treatment
ADD Dosage INTEGER(99) DEFAULT 0 NOT NULL;
ALTER TABLE Treatment
MODIFY T_Name Treatment_Name VARCHAR(30);
DROP TABLE Treatment;
ALTER TABLE Patient_Treatment DROP FOREIGN KEY PT_PID_FK;
<<
OR >>
ALTER TABLE Patient_Treatment DROP INDEX PT_PID_FK;
ALTER TABLE Patient_Treatment DROP FOREIGN KEY PT_TID_FK;
<<
OR >>
ALTER TABLE Patient_Treatment DROP INDEX PT_TID_FK;