CREATE TABLE Patient(
    PID INTEGER(7) PRIMARY KEY NOT NULL,
    P_Name VARCHAR(30) NOT NULL
);
CREATE TABLE Treatment(
    TID INTEGER(7) PRIMARY KEY NOT NULL,
    T_Name VARCHAR(30) NOT NULL
);
CREATE TABLE Patient_Treatment(
    PID_PT INTEGER(7) NOT NULL,
    TID_PT INTEGER(7) NOT NULL,
    Due_Date DATETIME NOT NULL,
    CONSTRAINT PRIMARY KEY(PID_PT, TID_PT),
    CONSTRAINT PID_PT_FK FOREIGN KEY (PID_PT) REFERENCES Patient(PID) ON DELETE CASCADE,
    CONSTRAINT TID_PT_FK FOREIGN KEY (TID_PT) REFERENCES Treatment(TID) ON DELETE CASCADE
);